[project]
name = "hdxw-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "flask>=3.1.1",
    "lxml>=6.0.0",
    "mysql-connector-python>=9.4.0",
    "requests>=2.32.4",
]
